---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cos-auditd-fluent-bit-config
  namespace: cos-auditd
  annotations:
    kubernetes.io/description: 'ConfigMap for Linux auditd logging daemonset on COS nodes.'
data:
  fluent-bit.conf: |-
    [SERVICE]
        Flush         5
        Grace         120
        Log_Level     info
        Daemon        off
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_PORT     2024

    [INPUT]
        # https://docs.fluentbit.io/manual/input/systemd
        Name            systemd
        Alias           audit
        Tag             audit
        Systemd_Filter  SYSLOG_IDENTIFIER=audit
        Path            /var/log/journal
        DB              /var/lib/cos-auditd-fluent-bit/pos-files/audit.db
        Buffer_Max_Size 20MB
        Mem_Buf_Limit   20MB

    [FILTER]
        # https://docs.fluentbit.io/manual/pipeline/filters/modify
        Name                modify
        Match               audit
        Add                 logging.googleapis.com/local_resource_id k8s_node.${NODE_NAME}

    [FILTER]
        Name           modify
        Match          audit
        Add            logging.googleapis.com/logName linux-auditd

    [OUTPUT]
        # https://docs.fluentbit.io/manual/pipeline/outputs/stackdriver
        Name                      stackdriver
        Match                     audit
        Severity_key              severity
        log_name_key              logging.googleapis.com/logName
        Resource                  k8s_node
        # The plugin will read the project ID from the metadata server, but not the cluster name and location for some reason, so they have to be injected.
        k8s_cluster_name          ${CLUSTER_NAME}
        k8s_cluster_location      ${CLUSTER_LOCATION}
        net.connect_timeout       60
        Retry_Limit               14
        Workers                   2