apiVersion: v1
kind: Service
metadata:
  name: nginx-service-2
  namespace: gke00568-non-compliant-ns
  labels:
    app.kubernetes.io/name: nginx
spec:
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
